import jsPDF from 'jspdf';
import JSZip from 'jszip';

// ── Markdown export ───────────────────────────────────────
export function toMarkdown(item) {
  const date = new Date(item.createdAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  return `# ${item.contentType.toUpperCase()} — ${item.workspaceName || 'BrandFlow'}

**Platform:** ${item.platform || item.contentType}
**Tone:** ${item.tone}
**Topic:** ${item.topic}
**Generated:** ${date}

---

${item.content}

---
*Generated by BrandFlow AI*
`;
}

// ── PDF export ────────────────────────────────────────────
export function exportPDF(item) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageW - margin * 2;

  // Header bar
  doc.setFillColor(79, 124, 255);
  doc.rect(0, 0, pageW, 18, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('BrandFlow AI', margin, 12);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('AI-Powered Social Media Content', pageW - margin, 12, { align: 'right' });

  // Title
  doc.setTextColor(20, 20, 40);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text(item.contentType.toUpperCase() + ' CONTENT', margin, 34);

  // Meta info
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100, 110, 140);
  const date = new Date(item.createdAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  doc.text(`Platform: ${item.platform || item.contentType}  |  Tone: ${item.tone}  |  ${date}`, margin, 42);
  doc.text(`Topic: ${item.topic}`, margin, 49);

  // Divider
  doc.setDrawColor(220, 225, 240);
  doc.line(margin, 54, pageW - margin, 54);

  // Content
  doc.setTextColor(30, 35, 55);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  const lines = doc.splitTextToSize(item.content, maxWidth);
  let y = 64;
  const lineH = 6.5;
  for (const line of lines) {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.text(line, margin, y);
    y += lineH;
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(160, 170, 200);
  doc.text('Generated by BrandFlow AI — brandflow.app', margin, 285);

  doc.save(`brandflow-${item.contentType}-${Date.now()}.pdf`);
}

// ── Single markdown file download ────────────────────────
export function exportMarkdown(item) {
  const content = toMarkdown(item);
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `brandflow-${item.contentType}-${Date.now()}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

// ── ZIP export (multiple items) ───────────────────────────
export async function exportZIP(items, workspaceName = 'BrandFlow') {
  const zip = new JSZip();
  const folder = zip.folder(workspaceName.replace(/\s+/g, '_'));

  // Individual markdown files
  const mdFolder = folder.folder('markdown');
  items.forEach((item, i) => {
    mdFolder.file(`${i + 1}_${item.contentType}_${item.topic.slice(0, 20).replace(/\s+/g, '_')}.md`, toMarkdown(item));
  });

  // JSON data
  folder.file('content_data.json', JSON.stringify({ workspace: workspaceName, exportedAt: new Date().toISOString(), items }, null, 2));

  // Summary
  const summary = `# ${workspaceName} — Content Export
Exported: ${new Date().toLocaleDateString()}
Total items: ${items.length}

## Content Summary
${items.map((item, i) => `${i + 1}. ${item.contentType.toUpperCase()} — ${item.topic} (${item.platform || 'All'})`).join('\n')}

Generated by BrandFlow AI
`;
  folder.file('README.md', summary);

  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${workspaceName.replace(/\s+/g, '_')}_content_${Date.now()}.zip`;
  a.click();
  URL.revokeObjectURL(url);
}

// ── JSON export ───────────────────────────────────────────
export function exportJSON(items, workspaceName) {
  const data = { workspace: workspaceName, exportedAt: new Date().toISOString(), count: items.length, items };
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `brandflow-${workspaceName.replace(/\s+/g, '_')}-${Date.now()}.json`;
  a.click();
  URL.revokeObjectURL(url);
}
